# Generated by Django 6.0.3 on 2026-03-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asked_question', models.TextField()),
                ('answer', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('anon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.anon')),
            ],
        ),
        migrations.CreateModel(
            name='FAQuestionsSubmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('desc', models.CharField(max_length=600)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('anon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.anon')),
            ],
        ),
    ]
