# Generated by Django 6.0.3 on 2026-04-03 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('desc', models.CharField(max_length=400, verbose_name='Description')),
                ('account_created_date', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('desc', models.CharField(blank=True, max_length=600, null=True)),
                ('answer', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('answered_date', models.DateTimeField()),
                ('deletion_date', models.DateTimeField(null=True)),
                ('anon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persistence.anon')),
            ],
        ),
    ]
