# Generated by Django 6.0.3 on 2026-04-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faquestions',
            name='answered_date',
            field=models.DateTimeField(null=True),
        ),
    ]
