# Generated by Django 6.0.3 on 2026-04-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_date', models.DateTimeField(auto_created=True)),
                ('image', models.ImageField(height_field=1080, upload_to='', width_field=1920)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('desc', models.CharField(max_length=400, verbose_name='Description')),
            ],
        ),
    ]
