# Generated by Django 6.0.3 on 2026-04-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_content', models.CharField(max_length=200, verbose_name='Log Contents')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
