# Generated by Django 6.0.3 on 2026-04-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0005_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, height_field=1080, null=True, upload_to='', width_field=1920),
        ),
    ]
