# Generated by Django 6.0.3 on 2026-04-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0006_alter_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='GitHub Url'),
        ),
    ]
