# Generated by Django 6.0.3 on 2026-04-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0007_projects_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projects',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
