# Generated by Django 6.0.3 on 2026-04-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0008_alter_projects_image_alter_projects_uploaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_img'),
        ),
    ]
