# Generated by Django 6.0.3 on 2026-04-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0009_alter_projects_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currently_online_user_count', models.PositiveIntegerField(default=0)),
                ('currently_offline_user_count', models.PositiveIntegerField(default=0)),
                ('currently_online_anon_count', models.PositiveIntegerField(default=0)),
                ('registered_user_count', models.PositiveIntegerField(default=0)),
                ('currently_online_admin_count', models.SmallIntegerField(default=0)),
                ('currently_offline_admin_count', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
