# Generated by Django 6.0.3 on 2026-04-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0010_sitestatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitestatistics',
            name='total_anon_user_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
