# Generated by Django 6.0.3 on 2026-04-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0011_sitestatistics_total_anon_user_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon',
            name='activity_status',
            field=models.BooleanField(default=False),
        ),
    ]
