# Generated by Django 6.0.3 on 2026-04-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0013_alter_anon_last_seen_alter_feedback_time_viewed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitestatistics',
            old_name='currently_online_anon_count',
            new_name='currently_online_anon_user_count',
        ),
    ]
