# Generated by Django 5.2.7 on 2026-03-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_ip_addr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='ip_addr',
        ),
    ]
