# Generated by Django 5.2.7 on 2026-03-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('desc', models.CharField(max_length=400, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
                ('time_viewed', models.TimeField(auto_now=True)),
            ],
        ),
    ]
