# Generated by Django 5.2.7 on 2026-03-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ip_addr',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
    ]
