# Generated by Django 5.2.7 on 2026-03-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_ip_addr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(default=0, max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
