# Generated by Django 6.0.3 on 2026-03-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_feedback_name_feedback_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ip_addr',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
    ]
