# Generated by Django 6.0.3 on 2026-03-05 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('feedback', '0005_feedback_ip_addr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='ip_addr',
        ),
        migrations.AddField(
            model_name='feedback',
            name='anon',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.anon'),
            preserve_default=False,
        ),
    ]
