# Generated by Django 6.0.3 on 2026-03-06 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('feedback', '0006_remove_feedback_ip_addr_feedback_anon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='anon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.anon'),
        ),
    ]
