# Generated by Django 6.0.3 on 2026-04-03 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='Name')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('anon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persistence.anon')),
            ],
        ),
    ]
