# Generated by Django 6.0.3 on 2026-04-02 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
        ('persistance', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='anon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persistance.anon'),
        ),
    ]
