# Generated by Django 6.0.3 on 2026-04-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('chatting', '0002_alter_message_anon'),
        ('feedback', '0008_alter_feedback_anon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anon',
        ),
    ]
