# Generated by Django 6.0.3 on 2026-03-06 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faquestions',
            name='anon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.anon'),
        ),
        migrations.AlterField(
            model_name='faquestionssubmissions',
            name='anon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.anon'),
        ),
    ]
